# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/接口关联demo/login_demo.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseLoginDemo(HttpRunner):

    config = Config("登陆接口").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("登录接口")
            .post("/member/login")
            .with_headers(**{"X-Lemonban-Media-Type": "lemonban.v2"})
            .with_data(
                {"mobile_phone": "$mobile_phone", "pwd": "$pwd", "code": "$code"}
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginDemo().test_start()
