# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/接口关联demo/relation.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from testcases.接口关联demo.register_demo_test import TestCaseRegisterDemo as RegisterDemo
from testcases.接口关联demo.login_demo_test import TestCaseLoginDemo as LoginDemo


class TestCaseRelation(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"mobile_phone-pwd": "${P(csv_data/mobile_phone-pwd.csv)}"})
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("关联测试用例").base_url("${ENV(base_url)}")

    teststeps = [
        Step(RunTestCase("注册接口").call(RegisterDemo).export(*["code"])),
        Step(RunTestCase("登录接口").call(LoginDemo)),
    ]


if __name__ == "__main__":
    TestCaseRelation().test_start()
