# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/ymlCaseDemo/extract_variables_yml.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseExtractVariablesYml(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "mobile_phone": ["133000000102", "133000000103", "133000000104"],
                "pwd": ["Aa123456"],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("post请求测试demo").variables(**{"base_url": "http://api.lemonban.com"})

    teststeps = [
        Step(
            RunRequest("注册接口")
            .post("$base_url/futureloan/member/register")
            .with_headers(**{"X-Lemonban-Media-Type": "lemonban.v2"})
            .with_data({"mobile_phone": "$mobile_phone", "pwd": "$pwd"})
            .extract()
            .with_jmespath("body.code", "code")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("登录接口")
            .post("http://api.lemonban.com/futureloan/member/login")
            .with_headers(**{"X-Lemonban-Media-Type": "lemonban.v2"})
            .with_data(
                {"mobile_phone": "$mobile_phone", "pwd": "$pwd", "code": "$code"}
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseExtractVariablesYml().test_start()
