# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/ymlCaseDemo/login_sms.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseLoginSms(HttpRunner):

    config = Config("登录接口")

    teststeps = [
        Step(
            RunRequest("登录接口")
            .with_variables(**{"test": "test"})
            .post("${ENV(base_url)}/api/leapp/login/login-sms")
            .with_headers(
                **{"Content-Type": "application/json;charset=UTF-8", "god": "true"}
            )
            .with_json(
                {
                    "loginName": "",
                    "mobile": "16000005576",
                    "password": "",
                    "smsCode": "123456",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.desc", "成功")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginSms().test_start()
