# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/ymlCaseDemo/parameters_csv.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCaseParametersCsv(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "mobile_phone": ["133000000096", "133000000097", "133000000098"],
                "pwd": ["Aa123456", "", "A"],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("post请求测试demo").variables(**{"file": "case_file/Lemon_mobile.csv"})

    teststeps = [
        Step(
            RunRequest("登录接口")
            .post("http://api.lemonban.com/futureloan/member/login")
            .with_headers(**{"X-Lemonban-Media-Type": "lemonban.v2"})
            .with_data({"mobile_phone": "$mobile_phone", "pwd": "$pwd"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseParametersCsv().test_start()
