# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases\ymlCaseDemo\post请求demo请求.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCasePost请求Demo请求(HttpRunner):

    config = Config("post请求测试demo")

    teststeps = [
        Step(
            RunRequest("登录接口")
            .post("http://api.lemonban.com/futureloan/member/login")
            .with_headers(**{"X-Lemonban-Media-Type": "lemonban.v2"})
            .with_data({"mobile_phone": "13300000100", "pwd": "Aa123456"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCasePost请求Demo请求().test_start()
