# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases\ymlCaseDemo\post请求demo请求.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters


class TestCasePost请求Demo请求(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "mobile_phone-pwd": [
                    ["13300000097", "Aa123456"],
                    ["13300000098", "Aa123456"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("post请求测试demo")

    teststeps = [
        Step(
            RunRequest("登录接口")
            .post("http://api.lemonban.com/futureloan/member/login")
            .with_headers(**{"X-Lemonban-Media-Type": "lemonban.v2"})
            .with_data({"mobile_phone": "$mobile_phone", "pwd": "$pwd"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCasePost请求Demo请求().test_start()
