# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/ymlCaseDemo/Yml_demo2.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseYmlDemo2(HttpRunner):

    config = Config("yml测试用例")

    teststeps = [
        Step(
            RunRequest("yml测试用例")
            .with_variables(**{"test": "test"})
            .get("http://www.fairytest.com/api/demand/getPageLink")
            .with_params(**{"test": "test"})
            .with_headers(**{"Content-Type": "application/json;charset=UTF-8"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 412)
            .assert_equal("$..code", [412])
        ),
    ]


if __name__ == "__main__":
    TestCaseYmlDemo2().test_start()
