# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/ymlCaseDemo/Yml_demo.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseYmlDemo(HttpRunner):

    config = Config("GET请求测试用例").variables(
        **{
            "base_url": "http://www.fairytest.com",
            "test": "test",
            "expect_body_code": 412,
        }
    )

    teststeps = [
        Step(
            RunRequest("GET请求测试用例")
            .get("${base_url}/api/demand/getPageLink")
            .with_params(**{"test": "${test}"})
            .with_headers(**{"Content-Type": "application/json;charset=UTF-8"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", "$expect_body_code")
        ),
    ]


if __name__ == "__main__":
    TestCaseYmlDemo().test_start()
