# 测试项目名称
project_name: 小柒的测试项目

# 域名1
host: https://www.wanandroid.com
# 域名2，支持多个域名配置
app_host:

env: 测试环境

# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 小柒测试笔记

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
notification_type: 3


# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 重要的事情说三遍

# 注意点：
# 之前为了小伙伴们拉下代码执行的时候不受影响，企业微信、钉钉、邮箱的通知配置的都是我的
# 我发现很多拉代码的小伙伴这里配置都没改，所有的通知都发到我这里来了哦~~麻烦看到这里的小伙伴自己改一下相关配置

email:
  send_user: 43730829@qq.com
  email_host: smtp.qq.com
  # 自己到QQ邮箱中配置stamp_key
  stamp_key: urisgnhscxndbhch
  # 收件人改成自己的邮箱
  send_list: 43730829@qq.com

# 飞书通知
lark:
  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/96025325-4ab6-4691-ae0c-e02956d47a75

# 钉钉相关配置
ding_talk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=6b147ac370733c7417a5f9c32ea6eb7c0f8e7297a309dc4ebeef26a09bab707e
  secret: SEC69f165aaf17ea11aa3dcdd8faf1cf370b324c474d4c009e30fd6c791b9f0032d

# 企业通知的相关配置
wechat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=5e6bfeaf-d1d9-423b-a489-6a92a922bf65